# Generated by Django 6.1 on 2026-08-13 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employee_id", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(max_length=15)),
                ("department", models.CharField(max_length=100)),
                ("role", models.CharField(max_length=100)),
                ("joining_date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("asset_name", models.CharField(max_length=100)),
                ("asset_id", models.CharField(max_length=30, unique=True)),
                ("asset_tag", models.CharField(max_length=30, unique=True)),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("Laptop", "Laptop"),
                            ("Desktop", "Desktop"),
                            ("Monitor", "Monitor"),
                            ("Printer", "Printer"),
                            ("Phone", "Phone"),
                            ("Other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("brand", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
                ("serial_number", models.CharField(max_length=100, unique=True)),
                ("purchase_date", models.DateField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Available", "Available"),
                            ("Assigned", "Assigned"),
                            ("Repair", "Repair"),
                        ],
                        default="Available",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assets",
                        to="asset.employee",
                    ),
                ),
            ],
        ),
    ]
