# Generated by Django 6.1 on 2026-08-15 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asset", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="asset_type",
            field=models.CharField(
                choices=[
                    ("Laptop", "Laptop"),
                    ("Desktop", "Desktop"),
                    ("Monitor", "Monitor"),
                    ("Printer", "Printer"),
                    ("Phone", "Phone"),
                    ("Other", "Other"),
                    ("Server", "Server"),
                    ("Tablet", "Tablet"),
                    ("Keyboard", "Keyboard"),
                    ("Mouse", "Mouse"),
                ],
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("Asset Added", "Asset Added"),
                            ("Asset Assigned", "Asset Assigned"),
                            ("Asset Returned", "Asset Returned"),
                            ("Sent for Repair", "Sent for Repair"),
                            ("Repair Completed", "Repair Completed"),
                            ("Asset Updated", "Asset Updated"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="asset.asset",
                    ),
                ),
            ],
        ),
    ]
