# Generated by Django 6.1 on 2026-08-15 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asset", "0002_alter_asset_asset_type_activity"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="employee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="activities",
                to="asset.employee",
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="performed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="performed_activities",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="action",
            field=models.CharField(
                choices=[
                    ("Employee Added", "Employee Added"),
                    ("Employee Updated", "Employee Updated"),
                    ("Asset Added", "Asset Added"),
                    ("Asset Assigned", "Asset Assigned"),
                    ("Asset Returned", "Asset Returned"),
                    ("Sent for Repair", "Sent for Repair"),
                    ("Repair Completed", "Repair Completed"),
                    ("Asset Updated", "Asset Updated"),
                    ("Asset Deleted", "Asset Deleted"),
                    ("Login", "Login"),
                    ("Logout", "Logout"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="asset",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="activities",
                to="asset.asset",
            ),
        ),
    ]
