# Generated by Django 6.1 on 2026-08-26 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0005_ticketcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='ticket_screenshots/'),
        ),
    ]
