# Generated by Django 6.1 on 2026-08-26 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0006_ticket_screenshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_escalated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='activity',
            name='action',
            field=models.CharField(choices=[('Employee Added', 'Employee Added'), ('Employee Updated', 'Employee Updated'), ('Asset Added', 'Asset Added'), ('Asset Assigned', 'Asset Assigned'), ('Asset Returned', 'Asset Returned'), ('Sent for Repair', 'Sent for Repair'), ('Repair Completed', 'Repair Completed'), ('Asset Updated', 'Asset Updated'), ('Asset Deleted', 'Asset Deleted'), ('Login', 'Login'), ('Logout', 'Logout'), ('SLA Escalation', 'SLA Escalation')], max_length=50),
        ),
    ]
